name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
  
jobs:
  qodana-rf-api:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v3
        
      - name: Skip the API scan
        id: skip-scan
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths: '["remote-falcon-api/**"]'
        
      - name: Scan the project
        if: steps.skip-scan.outputs.should_skip != 'true'
        uses: JetBrains/qodana-action@v2023.2
        timeout-minutes: 20
        with:
          args: --project-dir,remote-falcon-api
          results-dir: ${{ runner.temp }}/qodana/results-rf-api
          artifact-name: qodana-report-rf-api
          cache-dir: ${{ runner.temp }}/qodana/caches-rf-api
          additional-cache-hash: ${{ github.sha }}-rf-api
          pr-mode: false # otherwise, it adds the --changes flag and the check fails
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
  qodana-rf-web:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v3
        
      - name: Skip the Web scan
        id: skip-scan
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths: '["remote-falcon-web/**"]'
        
      - name: Scan the project
        if: steps.skip-scan.outputs.should_skip != 'true'
        uses: JetBrains/qodana-action@v2023.2
        timeout-minutes: 20
        with:
          args: --project-dir,remote-falcon-web
          results-dir: ${{ runner.temp }}/qodana/results-rf-web
          artifact-name: qodana-report-rf-web
          cache-dir: ${{ runner.temp }}/qodana/caches-rf-web
          additional-cache-hash: ${{ github.sha }}-rf-web
          pr-mode: false # otherwise, it adds the --changes flag and the check fails
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
